### ISSUE TITLE
Use ruler over HTML5 Canvas?

### ISSUE THREAD

**Issue by ekhanh101** [MrFrankel/ruler#4]
Hi, this ruler is great!
How would you use this around an HTML5 canvas?

I've tried, something like
    <div id="rulerwrapper">
        <canvas id="c" width="720" height="405" style="border:1px solid red;float:left;"></canvas>        
    </div>

**Comment by MrFrankel** [comment]
@ekhanh101, Thanks, great to hear!
Not quit sure I understand the question though...

**Comment by ekhanh101** [comment]
Hi,
I was wondering how do i wrap your guides around an HTML5 canvas?

I would like to do the rulers guides.

Do i just put my div inside your wrapper div? that didn't seem to work.
do you have an example i can see?

**Comment by MrFrankel** [comment]
@ekhanh101 Hey,
ive fixed the README and the demo. hope that is enough for you to get it working they way you want.
Let me know if you need anything else
